# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 01:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='userprofile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.CharField(choices=[('customer', 'customer'), ('chef', 'chef'), ('manager', 'manager'), ('delivery man', 'delivery man')], default='customer', max_length=20)),
            ],
        ),
    ]
