# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 21:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user_type', models.CharField(choices=[('Customer', 'Customer'), ('Chef', 'Chef'), ('Manager', 'Manager'), ('elivery man', 'Delivery man')], max_length=10)),
                ('vip_user', models.BooleanField(default=False, verbose_name='VIP User')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active User')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
