# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='is_vip',
            new_name='is_VIP',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(default='', max_length=100),
        ),
    ]
