# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0005_auto_20170318_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyRegistrationSupplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(help_text='Please fill your real name', max_length=100, verbose_name='Real name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('user_type', models.CharField(choices=[('customer', 'customer'), ('chef', 'chef'), ('manager', 'manager'), ('delivery man', 'delivery man')], default='customer', max_length=20)),
                ('registration_profile', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='_supplementtut_myregistrationsupplement_supplement', to='registration.RegistrationProfile', verbose_name='registration profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
