# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplementtut', '0004_remove_myregistrationsupplement_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='myregistrationsupplement',
            name='address',
            field=models.TextField(blank=True, max_length=200, verbose_name="Customer's address"),
        ),
        migrations.AlterField(
            model_name='myregistrationsupplement',
            name='realname',
            field=models.CharField(help_text='Please fill your real name', max_length=100, verbose_name='Full Name'),
        ),
    ]
